spring.application.name=server


## database configuration
# Replace the placeholders with the actual values directly
jwt.secret=${JWT_SECRET}
jwt.expirationMs=${JWT_EXPIRATION_MS}

    spring.data.mongodb.uri=${MONGODB_URI}
