spring.application.name=server


## database configuration
# Replace the placeholders with the actual values directly
jwt.secret=hfaiehfisehfosndfejndfeswljrfeowfnjehwbewios4ngvhtrwglp4rkledf
jwt.expirationMs=3600000

spring.data.mongodb.uri=mongodb+srv://msaabbas6_db_user:eOXyVik93Z7BK4QU@cluster0.vfw4yfp.mongodb.net/mybudget?retryWrites=true&w=majority
