spring.application.name=server


## database configuration
spring.data.mongodb.uri=mongodb+srv://msaabbas6_db_user:eOXyVik93Z7BK4QU@cluster0.vfw4yfp.mongodb.net/?retryWrites=true&w=majority



jwt.secret=hfaiehfisehfosndfejndfeswljrfeowfnjehwbewios4ngvhtrwglp4rkledf
jwt.expirationMs=36000000